### ISSUE TITLE
Strings fix

### ISSUE THREAD

**Issue by crisdosaygo** [claytongulick/bit-sync#3]
It's "wasteful" but you can I think encode the JS UTF16 codepoints as UTF32 (eliminating surrogates), and then use `Uint32Array` to hold the characters, using:

```js
const utf32codes = new Uint32Array(Array.from(string).map(c => c.codePointAt(0)));
```

I suppose then your very cool JavaScript rsync algorithm implementation **bit-sync** would work on the `utf32codes.buffer` ! :p :) xx

**Comment by claytongulick** [comment]
interesting, I'm trying to think of the use case - wouldn't you need to hold a checksum document in memory alongside the string? Or maybe I'm not understanding? Would the use case here be arbitrary synchronization of a large string value across multiple remotes?

**Comment by crisdosaygo** [comment]
I might have misunderstood the purpose of your library. I was responding based on the idea that, "My library synchronizes arraybuffers between users, and works great, but it doesn't know how to work with strings." This, I believe solves, that. But it might not relate to what your library actually does! ;P ;) xx

I'm not sure what you mean by checksum document, but I don't think that would be necessary. 

> Would the use case here be arbitrary synchronization of a large string value across multiple remotes?

This turns your strings into binary so, because your library syncronizes binary, this will help it sync strings. 

Is that cool enough? :p ;) xx

**Comment by claytongulick** [comment]
Thanks! Yes, the purpose of the lib is to sync data between locations, but it's a little limited (based on the rsync algorithm) on how that actually happens. The magic of the rsync algorithm is that it supports sync in a single round trip. To achieve this, you create what's known as a "checksum document" which is a set of hashes for each block of length S. To get the data to synchronize, you send that checksum document, which creates a patch document, that's then applied.

The thorny bit there is that the creation of the checksum document is a relatively processor intensive operation - not generally something you'd want to do in real-time for large data.

I like your methodology of converting a string to arraybuffer! The operational challenge there would be creating and caching the checksum document along with the created array buffer. 

Rsync, historically, has been used for file synchronization due to this, where you can create and cache the checksum doc next to the file.

For abstractions like strings, I think most people prefer things like OT or CRDTs or somesuch for syncing/collaboration?
